# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gypsy Moths
email: your-email@domain.com
description:


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
port: 4000

# Social media profiles - feel free to add more here
twitter_username: SBootstrap
facebook_username: StartBootstrap
#instagram_username: beyonce

# Build settings
markdown: kramdown
